language:
- generic
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-xetex
    - latexmk
    - texlive-fonts-recommended
    - texlive-lang-italian
    - fonts-lmodern
    - latex-xcolor
script:
- xelatex Curriculum
after_failure:
- cat Curriculum.log

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SvusBsiu+cmFS+Wn/wpFv3mW4kMvAIvpxZiVyIxw5sUllbi6QHQDE7+fw6i521n4NCnXSj8fkG4RjvpldUe+F+7dNTbRO++FrZVQ8Pag2CweDkAEL6IQ8ZaERzme0utWu68w2GVND4SvWCyZydsx3YkqwDRUIKXustD3XfmGXMfSEguSQjTD9UcHOAF9bLfQQP+1QgD+3BNLgH453YrgGg7lxDMp7MuT482GK4Qu2zWO+FKc2ngI3mc/VpSQz+kKKy/oeGTdEwAlNqMrm0GBjDQxTVllChkiKTPTaIOo1mmkCXrlLpnverz5/Zm/p1/Bf9raj10g46pFypsvVvpZT6q7ExkjjyGc/Fr7ecg1ogOaz8t1c0H9ysM37003IKYYmceGLU00bHuijU9CAsWvNzz6MQwJTHuotQb1n8pfh2cMCcTYUUGwO+eEPH++ZJONeY0iZRJ9WM7jPJZ1GJ2mqrwyI0ptRMaPRdzsbfWFrpNHypWmCvAZLcY79oeWxnG5nP61tj9uOQ6LvTv06ok7eRuRj11Wq8eS8CNqz6qSvm5OqZKNbYJyLtdimQzL4aEzC44c+dIfi3DnvTloWOWg6xOIgBN9bWlo7WjVda3ZrWz5RY8Bo2tmEchdeAOac08+e0HHOlKGMH/dEcsmQm20vusTeWRQ8r6xS3zPKUE9BAI=
  file: Curriculum.pdf
  on:
    all_branches: true
    tags: true
