language:
- generic
dist: trusty
sudo: true
addons:
  apt:
    packages:
    - texlive-latex-extra
    - texlive-xetex
    - latexmk
    - texlive-fonts-recommended
    - texlive-lang-italian
    - fonts-lmodern
    - latex-xcolor
script:
- xelatex Curriculum
after_failure:
- cat Curriculum.log

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: Curriculum.pdf
  on:
    branch: master
